[package]

name = "chainbuf"
version = "0.0.1"
authors = [ "Roma Sokolov <sokolov.r.v@gmail.com>" ]

[lib]
name = "chainbuf"
path = "src/lib.rs"
doctest = true

[features]
default = ["nix"]

[dependencies.nix]
git = "https://github.com/little-arhat/nix-rust"
branch = "compat-update-to-new-rustc"
optional = true

default-features = true

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[profile.test]
opt-level = 0
debug = true
